name: Upload build artifacts
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
  workflow_dispatch:
    inputs:
      commit:
        description: If the commit you want to test isn't the head of a branch, provide its SHA here
        required: false
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: npm run format-check
      - run: npm test

  artifacts:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    # Build artifacts are only needed for releasing workflow.
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Check out current commit
        # https://github.com/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ env.HEAD_COMMIT }}
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: pack
        run: npm pack
      - name: Archive artifacts
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.tgz
